from flask import Flask, render_template, request
from unidecode import unidecode
import sqlite3

app = Flask(__name__)

# Diccionario de materias (recortado por espacio, deberías copiar el completo)
materias = {
    "O1VJ305": {"nombre": "Game engines y diseño de niveles", "nivelacion": "actividades"},
    "O1EW301": {"nombre": "Introducción a la tecnología Web", "nivelacion": "actividades"},
    "O1EW308": {"nombre": "Seguridad y ética en la Web", "nivelacion": "actividades"},
    "L1CC113": {"nombre": "Política criminal", "nivelacion": "actividades"},
    "L1CC114": {"nombre": "Psicología criminal", "nivelacion": "actividades"},
    "L1CC125": {"nombre": "Psicopatología Criminal", "nivelacion": "actividades"},
    "L1CPA117": {"nombre": "Gobierno y asuntos públicos", "nivelacion": "actividades"},
    "L1AET111": {"nombre": "Geografía y patrimonio cultural internacional", "nivelacion": "actividades"},
    "L1DSE104": {"nombre": "Naturaleza y sociedad", "nivelacion": "actividades"},
    "O1CA306": {"nombre": "e-Capacitación", "nivelacion": "actividades"},
    "L1CM112": {"nombre": "Elaboración de multimedios", "nivelacion": "actividades"},
    "O1AD308": {"nombre": "Entorno organizacional", "nivelacion": "actividades"},
    "O1OR304": {"nombre": "Administración del cambio organizacional", "nivelacion": "actividades"},
    "L1CM201": {"nombre": "Comunicación y procesos sociales contemporáneos", "nivelacion": "actividades"},
    "L1C122	": {"nombre": "Desarrollo en la adultez y senectud", "nivelacion": "actividades"},
    "O1CA307": {"nombre": "Desarrollo personal y profesional", "nivelacion": "actividades"},
    "L1PD110": {"nombre": "Tendencias actuales de la educación", "nivelacion": "actividades"},
    "O1AO306": {"nombre": "Administración de recursos en las operaciones empresariales", "nivelacion": "actividades"},
    "L1NE111": {"nombre": "Procedimientos y operaciones de comercio exterior", "nivelacion": "actividades"},
    "O1CI303": {"nombre": "Programas de fomento al comercio exterior", "nivelacion": "actividades"},
    "L1II112": {"nombre": "Seguridad e higiene industrial", "nivelacion": "actividades"},
    "O1LO306": {"nombre": "Ubicación física de instalaciones", "nivelacion": "actividades"},
    "O1AD301": {"nombre": "Administración de sistemas", "nivelacion": "actividades"},
    "O1WE307": {"nombre": "Arquitecturas y diseño de aplicaciones Web", "nivelacion": "actividades"},
    "O1DO304": {"nombre": "Integración de sistemas empresariales con software libre", "nivelacion": "actividades"},
    "O1IS306": {"nombre": "Métricas y arquitecturas de software", "nivelacion": "actividades"},
    "L1II113": {"nombre": "Procesos industriales", "nivelacion": "actividades"},
    "L1AD110": {"nombre": "Administración de PYMES", "nivelacion": "actividades"},
    "L1CO103": {"nombre": "Contabilidad administrativa", "nivelacion": "actividades"},
    "L1CO108": {"nombre": "Contabilidad intermedia", "nivelacion": "actividades"},
    "L1NE101": {"nombre": "Derecho aduanero I", "nivelacion": "actividades"},
    "L1NE103": {"nombre": "Derecho aduanero II", "nivelacion": "actividades"},
    "O1EM302": {"nombre": "Derecho aduanero", "nivelacion": "actividades"},
    "L1CO115": {"nombre": "Ética profesional y certificación", "nivelacion": "actividades"},
    "O1OR306": {"nombre": "Evaluación del desempeño y compensaciones", "nivelacion": "actividades"},
    "L1MK101": {"nombre": "Finanzas aplicadas a mercadotecnia", "nivelacion": "actividades"},
    "O1EN305": {"nombre": "Gestión de la cadena de valor", "nivelacion": "actividades"},
    "L1CO112": {"nombre": "ISR para personas físicas", "nivelacion": "actividades"},
    "L1CO110": {"nombre": "ISR para personas morales", "nivelacion": "actividades"},
    "O1LO307": {"nombre": "Logística y cultura de la calidad", "nivelacion": "actividades"},
    "L1NE108": {"nombre": "Logística y distribución internacional", "nivelacion": "actividades"},
    "O1RF305": {"nombre": "Riesgo de crédito", "nivelacion": "actividades"},
    "O1AO304": {"nombre": "Sistematización de procesos", "nivelacion": "actividades"},
    "O1ME307": {"nombre": "Técnicas de mediación para la solución de conflictos", "nivelacion": "actividades"},
    "L1CPA106": {"nombre": "Historia política de México", "nivelacion": "actividades"},
    "L1CPA101": {"nombre": "Introducción a la administración pública", "nivelacion": "actividades"},
    "O1CI308": {"nombre": "Relaciones gubernamentales e institucionales", "nivelacion": "actividades"},
    "L1CPA110": {"nombre": "Teoría política", "nivelacion": "actividades"},
    "L1PS111": {"nombre": "Intervención psicológica en las organizaciones", "nivelacion": "actividades"},
    "O1CR306": {"nombre": "Manejo de crisis y control de daños en comunicación", "nivelacion": "actividades"},
    "O1CR304": {"nombre": "Periodismo especializado", "nivelacion": "actividades"},
    "O1CO304": {"nombre": "Programación neurolingüística", "nivelacion": "actividades"},
    "O1CO308": {"nombre": "Taller de coaching ejecutivo", "nivelacion": "actividades"},
    "O1ME308": {"nombre": "Taller de mediación", "nivelacion": "actividades"},
    "L1IS104": {"nombre": "Algoritmos y estructuras de datos", "nivelacion": "actividades"},
    "O1AO307": {"nombre": "Desarrollo sustentable y ética ambiental", "nivelacion": "actividades"},
    "L1C107": {"nombre": "Estadística para negocios", "nivelacion": "actividades"},
    "O1AO308": {"nombre": "Creatividad e innovación tecnológica", "nivelacion": "actividades"},
    "O1CA305": {"nombre": "Dinámica de grupos", "nivelacion": "actividades"},
    "L1PD105": {"nombre": "Diseño curricular e instruccional", "nivelacion": "actividades"},
    "L1PD108": {"nombre": "Perspectiva de la educación superior", "nivelacion": "actividades"},
    "O1AP306": {"nombre": "Administración de controles de cambio", "nivelacion": "actividades"},
    "O1CA302": {"nombre": "Administración del cambio", "nivelacion": "actividades"},
    "O1OR302": {"nombre": "Análisis y valuación de puestos", "nivelacion": "actividades"},
    "O1CA308": {"nombre": "Competencias organizacionales", "nivelacion": "actividades"},
    "O1EN307": {"nombre": "Competitividad y crecimiento empresarial", "nivelacion": "actividades"},
    "O1EN306": {"nombre": "Desarrollo de habilidades directivas", "nivelacion": "actividades"},
    "L1OR204": {"nombre": "Desarrollo organizacional", "nivelacion": "actividades"},
    "L1CM203": {"nombre": "Diagnóstico y planeación de la comunicación organizacional", "nivelacion": "actividades"},
    "O1EN302": {"nombre": "Información económica y financiera", "nivelacion": "actividades"},
    "O1OR303": {"nombre": "Integración del capital humano", "nivelacion": "actividades"},
    "O1FI303": {"nombre": "Métodos cuantitativos para finanzas", "nivelacion": "actividades"},
    "L1AD107": {"nombre": "Principios de administración de procesos", "nivelacion": "actividades"},
    "L1II101": {"nombre": "Química", "nivelacion": "actividades"},
    "O1FI306": {"nombre": "Administración de la tesorería en una empresa", "nivelacion": "actividades"},
    "L1CO116": {"nombre": "Impuestos internacionales", "nivelacion": "actividades"},
    "O1RF302": {"nombre": "Normatividad en administración de riesgos", "nivelacion": "actividades"},
    "O1RF308": {"nombre": "Portafolios de inversión", "nivelacion": "actividades"},
    "L2FI202": {"nombre": "Tópicos financieros", "nivelacion": "actividades"},
    "O1TI306": {"nombre": "Calidad y técnicas de evaluación de los sistemas", "nivelacion": "actividades"},
    "O1AD302": {"nombre": "Entornos en la administración de sistemas", "nivelacion": "actividades"},
    "O1TI304": {"nombre": "Gestión de datos", "nivelacion": "actividades"},
    "L1CM202": {"nombre": "Medios y entornos de la comunicación digital", "nivelacion": "actividades"},
    "O1AO302": {"nombre": "Optimización de operaciones", "nivelacion": "actividades"},
    "L1II106": {"nombre": "Sistemas de manufactura", "nivelacion": "actividades"},
    "L2DE121": {"nombre": "Derecho administrativo ll", "nivelacion": "actividades"},
    "L1DE115": {"nombre": "Derecho administrativo", "nivelacion": "actividades"},
    "O2DE147": {"nombre": "Derecho electoral", "nivelacion": "actividades"},
    "L1EM311": {"nombre": "Régimen jurídico de inversión extranjera", "nivelacion": "actividades"},
    "O1IN301": {"nombre": "Sistema de la organización de las naciones unidas", "nivelacion": "actividades"},
    "O2DE151": {"nombre": "Sistema de organización de las naciones unidas (ONU)", "nivelacion": "actividades"},
    "L2DE120": {"nombre": "Títulos y Operaciones de Crédito", "nivelacion": "actividades"},
    "O1CI306": {"nombre": "Control de inventarios en operaciones de comercio exterior", "nivelacion": "actividades"},
    "O1EN301": {"nombre": "Entorno socioeconómico y estratégico de las empresas", "nivelacion": "actividades"},
    "O1FI304": {"nombre": "Finanzas corporativas", "nivelacion": "actividades"},
    "O1RF307": {"nombre": "Riesgo operativo", "nivelacion": "actividades"},
    "L1NE106": {"nombre": "Sistemas financieros", "nivelacion": "actividades"},
    "L1CPA127": {"nombre": "Economía", "nivelacion": "actividades"},
    "L1CM109": {"nombre": "Análisis de la información y la opinión pública", "nivelacion": "actividades"},
    "O1CR307": {"nombre": "Comunicación para la competitividad organizacional", "nivelacion": "actividades"},
    "O1IM307": {"nombre": "Comunicación y branding", "nivelacion": "actividades"},
    "L1CM204": {"nombre": "Comunicación y marketing", "nivelacion": "actividades"},
    "O1CD308": {"nombre": "Entretenimiento y medios digitales", "nivelacion": "actividades"},
    "L1MK103": {"nombre": "Mercadotecnia estratégica", "nivelacion": "actividades"},
    "L1MK108": {"nombre": "Mercadotecnia internacional", "nivelacion": "actividades"},
    "O1CR305": {"nombre": "Mercadotecnia social", "nivelacion": "actividades"},
    "O1IM306": {"nombre": "Mercadotecnia y redes sociales", "nivelacion": "actividades"},
    "L1CM108": {"nombre": "Periodismo digital", "nivelacion": "actividades"},
    "L1CM105": {"nombre": "Procesos globales de comunicación", "nivelacion": "actividades"},
    "O1CR308": {"nombre": "Producción de medios y mensajes para organizaciones", "nivelacion": "actividades"},
    "O1IM305": {"nombre": "Publicidad en medios masivos alternativos y digitales", "nivelacion": "actividades"},
    "L1MK111": {"nombre": "Publicidad y relaciones públicas", "nivelacion": "actividades"},
    "L1CM119": {"nombre": "Publicidad", "nivelacion": "actividades"},
    "L1CM116": {"nombre": "Relaciones públicas", "nivelacion": "actividades"},
    "O1IM301": {"nombre": "Semiótica", "nivelacion": "actividades"},
    "L1OR203": {"nombre": "Competencias del desarrollo humano", "nivelacion": "actividades"},
    "O1IM304": {"nombre": "Comunicación persuasiva", "nivelacion": "actividades"},
    "L1PS105": {"nombre": "Pruebas psicológicas", "nivelacion": "actividades"},
    "L1PS112": {"nombre": "Psicología organizacional", "nivelacion": "actividades"},
    "L1PS110": {"nombre": "Psicología social", "nivelacion": "actividades"},
    "O1CD301": {"nombre": "Internet I: la red como espacio de comunicación", "nivelacion": "actividades"},
    "O1CD303": {"nombre": "Internet II: la red como medio de información", "nivelacion": "actividades"},
    "O1WE301": {"nombre": "Lenguajes y estándares en la Web", "nivelacion": "actividades"},
    "O1WE304": {"nombre": "Métodos de desarrollo para Web", "nivelacion": "actividades"},
    "O1IS303": {"nombre": "Programación avanzada", "nivelacion": "actividades"},
    "O2DE153": {"nombre": "Auditoría Legal de las Empresas", "nivelacion": "actividades"},
    "O1RF306": {"nombre": "Riesgo de liquidez", "nivelacion": "actividades"},
    "O1RF304": {"nombre": "Riesgo de mercado", "nivelacion": "actividades"},
    "L1CO105": {"nombre": "Software para registro contable", "nivelacion": "actividades"},
    "L1CM117": {"nombre": "Ética y comunicación", "nivelacion": "actividades"},
    "L1PD109": {"nombre": "Evaluación del aprendizaje", "nivelacion": "actividades"},
    "L1PD107": {"nombre": "Tecnología educativa", "nivelacion": "actividades"},
    "O1PR302": {"nombre": "Amparo", "nivelacion": "actividades"},
    "L2DE118": {"nombre": "Amparo. Plan 2", "nivelacion": "actividades"},
    "L2DE111": {"nombre": "Bienes de derechos reales", "nivelacion": "actividades"},
    "L1DE107": {"nombre": "Bienes de derechos reales", "nivelacion": "actividades"},
    "L2DE119": {"nombre": "Contratos", "nivelacion": "actividades"},
    "L2DE132": {"nombre": "Derecho Laboral I", "nivelacion": "actividades"},
    "L2DE136": {"nombre": "Derecho laboral ll", "nivelacion": "actividades"},
    "L1DE118": {"nombre": "Derecho laboral", "nivelacion": "actividades"},
    "L2DE127": {"nombre": "Derecho notarial y correduría pública", "nivelacion": "actividades"},
    "L2DE112": {"nombre": "Medios alternativos de resolución de controversias", "nivelacion": "actividades"},
    "L2DE108": {"nombre": "Proceso Civil", "nivelacion": "actividades"},
    "L1DE114": {"nombre": "Procesos Jurisdiccionales B", "nivelacion": "actividades"},
    "L2DE140": {"nombre": "Seguridad social", "nivelacion": "actividades"},
    "L2DE141": {"nombre": "Delitos federales", "nivelacion": "actividades"},
    "L2DE128": {"nombre": "Derecho Concursal", "nivelacion": "actividades"},
    "L1DE120": {"nombre": "Derecho Internacional Privado B", "nivelacion": "actividades"},
    "L2DE133": {"nombre": "Derecho Internacional Privado", "nivelacion": "actividades"},
    "L1DE105": {"nombre": "Derecho Penal", "nivelacion": "actividades"},
    "L2DE142": {"nombre": "Ética del abogado", "nivelacion": "actividades"},
    "L2DE143": {"nombre": "Filosofía del derecho", "nivelacion": "actividades"},
    "L2DE122.-": {"nombre": "Juicio Oral civil y penal", "nivelacion": "actividades"},
    "L2DE122": {"nombre": "Procesos Constitucionales", "nivelacion": "actividades"},
    "O1OR305": {"nombre": "Relaciones laborales", "nivelacion": "actividades"},
    "L1EM307": {"nombre": "Seguros y fianzas", "nivelacion": "actividades"},
    "L2DE123": {"nombre": "Sucesiones", "nivelacion": "actividades"},
    "L1C103": {"nombre": "Sujetos del derecho mercantil", "nivelacion": "actividades"},
    "L2DE104": {"nombre": "Teoría General del Proceso", "nivelacion": "actividades"},
    "O1AP304": {"nombre": "Desarrollo de proyectos", "nivelacion": "actividades"},
    "L3HE404": {"nombre": "Equipos de alto desempeño", "nivelacion": "actividades"},
    "L1AD109": {"nombre": "Formulación y evaluación de proyectos de inversión", "nivelacion": "actividades"},
    "O1EN303": {"nombre": "Gestión de la innovación en la empresa", "nivelacion": "actividades"},
    "L1AD201": {"nombre": "Gestión en procesos de negocio", "nivelacion": "actividades"},
    "L1MK104": {"nombre": "Marcas y desarrollo de nuevos productos", "nivelacion": "actividades"},
    "O1ME302": {"nombre": "Técnicas de negociación", "nivelacion": "actividades"},
    "O1LO308": {"nombre": "Términos de comercio internacional", "nivelacion": "actividades"},
    "L1TI203": {"nombre": "Administración de servicios de TI", "nivelacion": "actividades"},
    "O1OR308": {"nombre": "Administración estratégica del capital humano", "nivelacion": "actividades"},
    "L1AET117": {"nombre": "Estructura de establecimientos de hospedaje", "nivelacion": "actividades"},
    "L1AET115": {"nombre": "Legislación turística", "nivelacion": "actividades"},
    "L1AV107": {"nombre": "Mercadotecnia integral y estratégica", "nivelacion": "actividades"},
    "L1MK110": {"nombre": "Mercadotecnia para organizaciones no lucrativas", "nivelacion": "actividades"},
    "L1CPA105": {"nombre": "Teoría de la administración pública", "nivelacion": "actividades"},
    "L1CPA112": {"nombre": "Teoría general de sistemas", "nivelacion": "actividades"},
    "L2DE117": {"nombre": "Derecho administrativo I", "nivelacion": "actividades"},
    "O2DE158": {"nombre": "Derecho anglosajón", "nivelacion": "actividades"},
    "L1DE106": {"nombre": "Derecho constitucional B", "nivelacion": "actividades"},
    "L2DE110": {"nombre": "Derecho constitucional", "nivelacion": "actividades"},
    "L2DE139": {"nombre": "Derecho Económico", "nivelacion": "actividades"},
    "L2DE126": {"nombre": "Derecho Fiscal I", "nivelacion": "actividades"},
    "L2DE130": {"nombre": "Derecho Fiscal II", "nivelacion": "actividades"},
    "O2DE146": {"nombre": "Derecho informático y nuevas tecnologías", "nivelacion": "actividades"},
    "L1DE113": {"nombre": "Derecho procesal administrativo", "nivelacion": "actividades"},
    "L2DE115": {"nombre": "Obligaciones", "nivelacion": "actividades"},
    "L2DE103": {"nombre": "Personas", "nivelacion": "actividades"},
    "O1CI301": {"nombre": "Régimen jurídico del comercio exterior", "nivelacion": "actividades"},
    "L1NE104": {"nombre": "Tratados internacionales y propiedad intelectual", "nivelacion": "actividades"},
    "L1CC121": {"nombre": "Seguridad pública y policiología", "nivelacion": "actividades"},
    "O1AD305": {"nombre": "Desarrollo e implementación de sistemas", "nivelacion": "actividades"},
    "O1EW307": {"nombre": "Dirección y planificación de proyectos Web", "nivelacion": "actividades"},
    "L1CM120": {"nombre": "Diseño de campañas", "nivelacion": "actividades"},
    "O1LO304": {"nombre": "Gestión de inventarios y almacenamiento", "nivelacion": "actividades"},
    "L1MK109": {"nombre": "Mercadotecnia industrial y de servicios", "nivelacion": "actividades"},
    "O1ME301": {"nombre": "Naturaleza del conflicto", "nivelacion": "actividades"},
    "O1TI301": {"nombre": "Sistemas de información", "nivelacion": "actividades"},
    "O1LO305": {"nombre": "Sistemas de transporte", "nivelacion": "actividades"},
    "L1IS101": {"nombre": "Arquitectura de computadoras", "nivelacion": "actividades"},
    "O1TI302": {"nombre": "Arquitecturas y dispositivos tecnológicos", "nivelacion": "actividades"},
    "O1SO302": {"nombre": "Automatización de procesos de negocio con software libre", "nivelacion": "actividades"},
    "O1TI307": {"nombre": "Control y seguridad de los sistemas", "nivelacion": "actividades"},
    "L1IS112": {"nombre": "Inteligencia artificial", "nivelacion": "actividades"},
    "L1IS109": {"nombre": "Lenguaje ensamblador", "nivelacion": "actividades"},
    "O1CI304": {"nombre": "Administración aduanera", "nivelacion": "actividades"},
    "O1TI308": {"nombre": "Administración de las TI", "nivelacion": "actividades"},
    "O1LO302": {"nombre": "Cadena de suministro", "nivelacion": "actividades"},
    "L1NE107": {"nombre": "Estrategia y competitividad internacional", "nivelacion": "actividades"},
    "O1LO301": {"nombre": "Logística empresarial", "nivelacion": "actividades"},
    "O1CI302": {"nombre": "Tratados y acuerdos comerciales", "nivelacion": "actividades"},
    "O1EW302": {"nombre": "Arquitectura y usabilidad Web", "nivelacion": "actividades"},
    "O1DO308": {"nombre": "Calidad para el desarrollo de software libre", "nivelacion": "actividades"},
    "O1VJ303": {"nombre": "Desarrollo de videojuegos 2D", "nivelacion": "actividades"},
    "O1VJ301": {"nombre": "Diseño de videojuegos", "nivelacion": "actividades"},
    "O1WE303": {"nombre": "Diseño y programación de interfaces de usuario Web", "nivelacion": "actividades"},
    "O1SO304": {"nombre": "Economía e iniciativas para promover el software libre", "nivelacion": "actividades"},
    "O1DO306": {"nombre": "Entornos y tecnologías de desarrollo", "nivelacion": "actividades"},
    "O1DO307": {"nombre": "Frameworks para el desarrollo Web", "nivelacion": "actividades"},
    "O1TI303": {"nombre": "Gestión del software base", "nivelacion": "actividades"},
    "O1AD306": {"nombre": "Infraestructura de sistemas", "nivelacion": "actividades"},
    "O1VJ304": {"nombre": "Inteligencia artificial y física en videojuegos", "nivelacion": "actividades"},
    "O1EW306": {"nombre": "Inteligencia de negocios en Web", "nivelacion": "actividades"},
    "O1DO301": {"nombre": "Introducción al software libre", "nivelacion": "actividades"},
    "O1TI305": {"nombre": "Modelos convergentes", "nivelacion": "actividades"},
    "O1EW304": {"nombre": "Modelos y procesos de negocio en Web", "nivelacion": "actividades"},
    "O1SO301": {"nombre": "Ofimática de software libre", "nivelacion": "actividades"},
    "O1VJ302": {"nombre": "Producción de recursos gráficos", "nivelacion": "actividades"},
    "O1IS305": {"nombre": "Programación de videojuegos", "nivelacion": "actividades"},
    "O1IS302": {"nombre": "Programación segmentada", "nivelacion": "actividades"},
    "O1AD307": {"nombre": "Seguridad y control", "nivelacion": "actividades"},
    "O1WE306": {"nombre": "Sistemas de seguridad en la Web", "nivelacion": "actividades"},
    "O1VJ307": {"nombre": "Videojuegos en plataformas móviles y consolas", "nivelacion": "actividades"},
    "O1VJ308": {"nombre": "Videojuegos multiplayer y en línea", "nivelacion": "actividades"},
    "L1AD204": {"nombre": "Administración de procesos", "nivelacion": "actividades"},
    "L1CO111": {"nombre": "Auditoría I", "nivelacion": "actividades"},
    "L1CO107": {"nombre": "Bases fiscales", "nivelacion": "actividades"},
    "L1MK107": {"nombre": "Ventas y administración de ventas", "nivelacion": "actividades"},
    "O1AP308": {"nombre": "Evaluación e indicadores del desempeño", "nivelacion": "actividades"},
    "L1PS109": {"nombre": "Evaluación psicológica en las organizaciones", "nivelacion": "actividades"},
    "O1CA303": {"nombre": "Programas de capacitación y desarrollo", "nivelacion": "actividades"},
    "L1PS106": {"nombre": "Psicología clínica", "nivelacion": "actividades"},
    "O1ME306": {"nombre": "Resolución de conflictos con terceras partes", "nivelacion": "actividades"},
    "L1CM102": {"nombre": "Teorías clásicas de la comunicación", "nivelacion": "actividades"},
    "O1WE305": {"nombre": "Administración de servidores Web", "nivelacion": "actividades"},
    "L1DSE111": {"nombre": "Conservación y preservación del medio ambiente", "nivelacion": "actividades"},
    "O1ME305": {"nombre": "Creatividad y pensamiento lateral", "nivelacion": "actividades"},
    "L1PD111": {"nombre": "Evaluación de programas e instituciones educativas", "nivelacion": "actividades"},
    "O1CA301": {"nombre": "Formación de instructores", "nivelacion": "actividades"},
    "O1CD302": {"nombre": "Multimedia: usos y apropiación social", "nivelacion": "actividades"},
    "O1CD304": {"nombre": "Producción audiovisual en plataformas digitales", "nivelacion": "actividades"},
    "O1EW305": {"nombre": "Sociedad de la información y la Web", "nivelacion": "actividades"},
    "O1ME303": {"nombre": "Taller de negociación de conflictos", "nivelacion": "actividades"},
    "O2DE148": {"nombre": "Argumentación jurídica", "nivelacion": "actividades"},
    "O2DE150": {"nombre": "Derecho de la integración europea", "nivelacion": "actividades"},
    "L2DE129": {"nombre": "Derecho internacional público", "nivelacion": "actividades"},
    "L2DE116": {"nombre": "Derecho Mercantil", "nivelacion": "actividades"},
    "L2DE144": {"nombre": "Derecho procesal laboral", "nivelacion": "actividades"},
    "L1NE102": {"nombre": "Introducción a los negocios internacionales", "nivelacion": "actividades"},
    "L2DE106": {"nombre": "Teoría del estado", "nivelacion": "actividades"},
    "L1DE103": {"nombre": "Teoría del Estado", "nivelacion": "actividades"},
    "O1FI308": {"nombre": "Ingeniería financiera", "nivelacion": "actividades"},
    "O1FI305": {"nombre": "Planeación financiera de la empresa", "nivelacion": "actividades"},
    "O1CI305": {"nombre": "Administración del tráfico internacional", "nivelacion": "actividades"},
    "O1WE308": {"nombre": "Aspectos éticos y legales de la Web", "nivelacion": "actividades"},
    "L1EM303": {"nombre": "Contratos en propiedad intelectual", "nivelacion": "actividades"},
    "O2DE156": {"nombre": "Contratos mercantiles internacionales y arbitraje", "nivelacion": "actividades"},
    "L2DE138": {"nombre": "Derecho Empresarial y Corporativo", "nivelacion": "actividades"},
    "L1DE126": {"nombre": "Derecho empresarial y corporativo", "nivelacion": "actividades"},
    "L1CM115": {"nombre": "Mercadotecnia", "nivelacion": "actividades"},
    "O1DO303": {"nombre": "Modelos de negocio y aspectos legales en torno al software libre", "nivelacion": "actividades"},
    "L1CPA114": {"nombre": "Políticas públicas", "nivelacion": "actividades"},
    "L2DE131": {"nombre": "Propiedad intelectual", "nivelacion": "actividades"},
    "O2DE145": {"nombre": "Sistemas de integración", "nivelacion": "actividades"},
    "O1ME304": {"nombre": "Comunicación efectiva", "nivelacion": "actividades"},
    "O1CO306": {"nombre": "Inteligencia emocional", "nivelacion": "actividades"},
    "L1CM114": {"nombre": "Métodos y técnicas de investigación social", "nivelacion": "actividades"},
    "L1PS104": {"nombre": "Teorías de la personalidad", "nivelacion": "actividades"},
    "L1DSE121": {"nombre": "Actividades ecoturísticas", "nivelacion": "actividades"},
    "L1DSE122": {"nombre": "Agroecología", "nivelacion": "actividades"},
    "L1DSE118": {"nombre": "Aprovechamiento y administración de los recursos naturales", "nivelacion": "actividades"},
    "L1DSE127": {"nombre": "Economía ecológica", "nivelacion": "actividades"},
    "L1DSE128": {"nombre": "Ecotecnicas", "nivelacion": "actividades"},
    "L1DSE117": {"nombre": "Ecoturismo", "nivelacion": "actividades"},
    "L1DSE116": {"nombre": "Ética y responsabilidad social", "nivelacion": "actividades"},
    "L1AET119": {"nombre": "Finanzas turísticas", "nivelacion": "actividades"},
    "L1DSE115": {"nombre": "Impacto ambiental", "nivelacion": "actividades"},
    "L1DSE123": {"nombre": "Legislación y políticas turísticas sustentables", "nivelacion": "actividades"},
    "L1DSE125": {"nombre": "Planeación ecoturísitca", "nivelacion": "actividades"},
    "L1DSE131": {"nombre": "Sistemas productivos sustentables", "nivelacion": "actividades"},
    "L1DSE126": {"nombre": "Tecnología ambiental", "nivelacion": "actividades"},
    "L1FI203": {"nombre": "Estadística para economía", "nivelacion": "actividades"},
    "L1FI201": {"nombre": "Matemáticas financieras", "nivelacion": "actividades"},
    "O1CR301": {"nombre": "Comunicación corporativa", "nivelacion": "actividades"},
    "O1CR302": {"nombre": "Comunicación institucional", "nivelacion": "actividades"},
    "O1CR303": {"nombre": "Comunicación política", "nivelacion": "actividades"},
    "L1CM111": {"nombre": "Estrategias de comunicación para organizaciones", "nivelacion": "actividades"},
    "O1LO303": {"nombre": "Estrategias de servicio al cliente", "nivelacion": "actividades"},
    "L1AV102": {"nombre": "Fundamentos de las ventas", "nivelacion": "actividades"},
    "L1CM107": {"nombre": "Guiones para medios de comunicación", "nivelacion": "actividades"},
    "L1CM101": {"nombre": "Historia de los medios", "nivelacion": "actividades"},
    "O1IM303": {"nombre": "Investigación de audiencias y mercados", "nivelacion": "actividades"},
    "O1CD305": {"nombre": "Mercadotecnia digital", "nivelacion": "actividades"},
    "L1MK106": {"nombre": "Promoción de ventas", "nivelacion": "actividades"},
    "O1EW303": {"nombre": "Web marketing", "nivelacion": "actividades"},
    "O1EN308": {"nombre": "Creación y desarrollo de nuevos negocios", "nivelacion": "actividades"},
    "L1NE110": {"nombre": "Elaboración de un plan de negocios", "nivelacion": "actividades"},
    "O1AP307": {"nombre": "Entrega de proyectos", "nivelacion": "actividades"},
    "O1FI307": {"nombre": "Evaluación de proyectos de inversión", "nivelacion": "actividades"},
    "O1IM302": {"nombre": "Fundamentos de expresión grafica y comunicación visual", "nivelacion": "actividades"},
    "O1EN304": {"nombre": "Gestión del cambio en la organización", "nivelacion": "actividades"},
    "O1CD307": {"nombre": "Implementación de programas de capacitación con medios digitales", "nivelacion": "actividades"},
    "O1CA304": {"nombre": "Intervención organizacional", "nivelacion": "actividades"},
    "L1AET102": {"nombre": "Introducción al estudio del turismo", "nivelacion": "actividades"},
    "O1AO305": {"nombre": "Normas y control de calidad", "nivelacion": "actividades"},
    "L1C112": {"nombre": "Plan de negocios", "nivelacion": "actividades"},
    "O1PR309": {"nombre": "Protección nacional de los derechos humanos", "nivelacion": "actividades"},
    "O2DE152": {"nombre": "Régimen de comercio exterior", "nivelacion": "actividades"},
    "O1AD304": {"nombre": "Sistemas en la empresa digital", "nivelacion": "actividades"},
    "L1CM110": {"nombre": "Teoría de la comunicación organizacional", "nivelacion": "actividades"},
    "L1DSE113": {"nombre": "Teoría turística", "nivelacion": "actividades"},
    "O1FI301": {"nombre": "Mercados financieros", "nivelacion": "examen"},
    "L1AD111": {"nombre": "Administración de empresas de servicios", "nivelacion": "examen"},
    "L1AD105": {"nombre": "Administración de programas de calidad", "nivelacion": "examen"},
    "L1CPA125": {"nombre": "Administración de recursos en el sector público", "nivelacion": "examen"},
    "L1AD203": {"nombre": "Administración del comportamiento organizacional", "nivelacion": "examen"},
    "L1CO109": {"nombre": "Administración financiera", "nivelacion": "examen"},
    "L1CPA113": {"nombre": "Administración pública (federal, estatal y municipal)", "nivelacion": "examen"},
    "L1C110": {"nombre": "Álgebra lineal", "nivelacion": "examen"},
    "L1C109": {"nombre": "Álgebra superior", "nivelacion": "examen"},
    "L1CO106": {"nombre": "Análisis e interpretación de estados financieros	", "nivelacion": "examen"},
    "L1IS108": {"nombre": "Análisis y diseño de sistemas", "nivelacion": "examen"},
    "L1PS101": {"nombre": "Bases biológicas del comportamiento", "nivelacion": "examen"},
    "L1IS106": {"nombre": "Bases de datos", "nivelacion": "examen"},
    "L1C113": {"nombre": "Bases filosóficas de la ciencia", "nivelacion": "examen"},
    "L1C108": {"nombre": "Bases jurídicas y mercantiles", "nivelacion": "examen"},
    "L1PD102": {"nombre": "Bases teóricas de la pedagogía", "nivelacion": "examen"},
    "L1C119": {"nombre": "Cálculo diferencial e integral", "nivelacion": "examen"},
    "O1CO303": {"nombre": "Coaching ontológico", "nivelacion": "examen"},
    "L3HE401": {"nombre": "Competencias gerenciales", "nivelacion": "examen"},
    "L1AD101": {"nombre": "Comportamiento organizacional", "nivelacion": "examen"},
    "O1IM308": {"nombre": "Comunicación aplicada a promoción y ventas", "nivelacion": "examen"},
    "L1C106": {"nombre": "Contabilidad administrativa y de costos", "nivelacion": "examen"},
    "L1CO104": {"nombre": "Contabilidad de costos", "nivelacion": "examen"},
    "L1CO101": {"nombre": "Contabilidad financiera I", "nivelacion": "examen"},
    "O1AO301": {"nombre": "Control estadístico de procesos y servicios", "nivelacion": "examen"},
    "L1CC106": {"nombre": "Criminalística", "nivelacion": "examen"},
    "L1CC101": {"nombre": "Criminología", "nivelacion": "examen"},
    "L2DE137": {"nombre": "Derecho ambiental", "nivelacion": "examen"},
    "L1EM308": {"nombre": "Derecho del consumidor", "nivelacion": "examen"},
    "L2DE114": {"nombre": "Derechos humanos y sus garantías", "nivelacion": "examen"},
    "L1IS103": {"nombre": "Desarrollo de páginas web", "nivelacion": "examen"},
    "L1C121": {"nombre": "Desarrollo en la niñez y adolescencia", "nivelacion": "examen"},
    "L1C123": {"nombre": "Desarrollo sustentable", "nivelacion": "examen"},
    "L1PD103": {"nombre": "Didáctica", "nivelacion": "examen"},
    "L1DSE102": {"nombre": "Educación ambiental", "nivelacion": "examen"},
    "L3HE402": {"nombre": "Eficiencia laboral", "nivelacion": "examen"},
    "L1PS107": {"nombre": "Entrevista psicológica", "nivelacion": "examen"},
    "L1C115": {"nombre": "Estadística para las ciencias sociales", "nivelacion": "examen"},
    "L1C125": {"nombre": "Estadística y probabilidad", "nivelacion": "examen"},
    "L1PD104": {"nombre": "Estrategias de enseñanza-aprendizaje", "nivelacion": "examen"},
    "L1C128": {"nombre": "Estructura de la industria de la transformación", "nivelacion": "examen"},
    "L1PS103": {"nombre": "Ética del psicólogo", "nivelacion": "examen"},
    "O1AP305": {"nombre": "Factor humano en la administración de proyectos", "nivelacion": "examen"},
    "L2DE107": {"nombre": "Familia", "nivelacion": "examen"},
    "O1CI307": {"nombre": "Financiamiento al comercio exterior", "nivelacion": "examen"},
    "L1NE109": {"nombre": "Financiamiento de las operaciones de comercio exterior", "nivelacion": "examen"},
    "L1C124": {"nombre": "Física", "nivelacion": "examen"},
    "L1C117": {"nombre": "Fundamentos de investigación", "nivelacion": "examen"},
    "L1PD101": {"nombre": "Fundamentos de la educación", "nivelacion": "examen"},
    "L1AET106": {"nombre": "Geografía y patrimonio cultural y nacional", "nivelacion": "examen"},
    "O1AO303": {"nombre": "Gestión de calidad", "nivelacion": "examen"},
    "L1C104": {"nombre": "Información financiera", "nivelacion": "examen"},
    "L1II102": {"nombre": "Ingenieria de métodos", "nivelacion": "examen"},
    "L1II104": {"nombre": "Ingeniería de sistemas", "nivelacion": "examen"},
    "L2DE101": {"nombre": "Instituciones de derecho romano", "nivelacion": "examen"},
    "L1CPA102": {"nombre": "Introducción a la ciencia política", "nivelacion": "examen"},
    "L1FI202": {"nombre": "Introducción a la información financiera", "nivelacion": "examen"},
    "L1C102": {"nombre": "Introducción a las matemáticas", "nivelacion": "examen"},
    "L1DE102": {"nombre": "Introducción al estudio del derecho", "nivelacion": "examen"},
    "L2DE102": {"nombre": "Introducción al estudio del derecho", "nivelacion": "examen"},
    "L1CM118": {"nombre": "Investigación aplicada a la comunicación", "nivelacion": "examen"},
    "L1C126": {"nombre": "Investigación de mercados", "nivelacion": "examen"},
    "L1II103": {"nombre": "Investigación de operaciones", "nivelacion": "examen"},
    "L1CM103": {"nombre": "Lectura y redacción", "nivelacion": "examen"},
    "L1II110": {"nombre": "Logística", "nivelacion": "examen"},
    "L1C111": {"nombre": "Matemáticas para los negocios", "nivelacion": "examen"},
    "L1AD202": {"nombre": "Mercados globales y finanzas personales", "nivelacion": "examen"},
    "L1C127": {"nombre": "Mercadotecnia integral", "nivelacion": "examen"},
    "L1CC127": {"nombre": "Métodos y técnicas de identificación humana", "nivelacion": "examen"},
    "O1AP301": {"nombre": "Métodos y técnicas para la administración de proyectos", "nivelacion": "examen"},
    "L1CPA120": {"nombre": "Modelo de toma de decisiones", "nivelacion": "examen"},
    "L1C105": {"nombre": "Organización y estructuras organizacionales", "nivelacion": "examen"},
    "L3HE403": {"nombre": "Pensamiento profesional", "nivelacion": "examen"},
    "L1CPA129": {"nombre": "Planeación gubernamental", "nivelacion": "examen"},
    "L1II111": {"nombre": "Planeación y control de la calidad", "nivelacion": "examen"},
    "L1II109": {"nombre": "Planeación y control de la producción", "nivelacion": "examen"},
    "L1AD102": {"nombre": "Planeación y control", "nivelacion": "examen"},
    "O1AP303": {"nombre": "Planificación de proyectos", "nivelacion": "examen"},
    "O1CPA138": {"nombre": "Presupuestos gubernamentales", "nivelacion": "examen"},
    "L1CC116": {"nombre": "Prevención del delito", "nivelacion": "examen"},
    "L1C101": {"nombre": "Principios y perspectivas de la administración", "nivelacion": "examen"},
    "L1PD106": {"nombre": "Problemas socioeconómicos de México", "nivelacion": "examen"},
    "O1CC136": {"nombre": "Problemas socioeconómicos de México-B", "nivelacion": "examen"},
    "L2DE113": {"nombre": "Proceso penal", "nivelacion": "examen"},
    "O1AP302": {"nombre": "Procesos en la administración de proyectos", "nivelacion": "examen"},
    "L2DE135": {"nombre": "Procesos Jurisdiccionales", "nivelacion": "examen"},
    "L1IS102": {"nombre": "Programación estructurada", "nivelacion": "examen"},
    "L1IS110": {"nombre": "Programación orientada a objetos", "nivelacion": "examen"},
    "L1PS108": {"nombre": "Psicología educativa", "nivelacion": "examen"},
    "L1IS113": {"nombre": "Redes de computadoras", "nivelacion": "examen"},
    "L1MK102": {"nombre": "Segmentación de mercados", "nivelacion": "examen"},
    "L1CC117": {"nombre": "Sistema penitanciario", "nivelacion": "examen"},
    "L1IS111": {"nombre": "Sistemas operativos", "nivelacion": "examen"},
    "L1CC105": {"nombre": "Sociología criminal", "nivelacion": "examen"},
    "L1II108": {"nombre": "Tecnología de información aplicada a las empresas", "nivelacion": "examen"},
    "L1II105": {"nombre": "Tecnología de materiales", "nivelacion": "examen"},
    "L1AD106": {"nombre": "Teoría de la organización", "nivelacion": "examen"},
    "L2DE105": {"nombre": "Teoría general del delito", "nivelacion": "examen"},
    "L1PS102": {"nombre": "Teorías de la motivación y la emoción", "nivelacion": "examen"},
    "L1C118": {"nombre": "Teorías del aprendizaje y la memoria", "nivelacion": "examen"},
    "L1C116": {"nombre": "Teorías del pensamiento y el lenguaje", "nivelacion": "examen"},
    "L1C114": {"nombre": "Teorías y sistemas de la psicología", "nivelacion": "examen"},
    "L1CO114": {"nombre": "Tópicos fiscales", "nivelacion": "examen"},
    "O1RF303": {"nombre": "Valuación de instrumentos financieros", "nivelacion": "examen"},
    "O1IS304": {"nombre": "Análisis y diseño orientado a objetos", "nivelacion": "actividades"},
    "O1VJ306": {"nombre": "Desarrollo de videojuegos 3D", "nivelacion": "actividades"},
    "O1WE302": {"nombre": "Desarrollo e integración de aplicaciones y servicios Web", "nivelacion": "actividades"},
    "O1DO305": {"nombre": "Ingeniería del software libre", "nivelacion": "actividades"},
    "O1IS301": {"nombre": "Programación", "nivelacion": "actividades"},
    "O1DO302": {"nombre": "Sistema operativo Linux", "nivelacion": "actividades"},
    "L1CC129": {"nombre": "Documentoscopía y grafoscopía", "nivelacion": "actividades"},
    "O1CO307": {"nombre": "Expresión corporal", "nivelacion": "actividades"},
    "L1CC126": {"nombre": "Informática criminal", "nivelacion": "actividades"},
    "L1CC120": {"nombre": "Victimología", "nivelacion": "actividades"},
    "L2DE125": {"nombre": "Derecho procesal administrativo y fiscal", "nivelacion": "actividades"},
    "L1CPA103": {"nombre": "Pensamiento social político", "nivelacion": "actividades"},
    "L1DSE103": {"nombre": "Cultura e interculturalidad", "nivelacion": "actividades"},
    "L1DSE106": {"nombre": "Biodiversidad", "nivelacion": "actividades"},
    "L1DSE105": {"nombre": "Ecología", "nivelacion": "actividades"},
    "L1DSE109": {"nombre": "Geografía turística", "nivelacion": "actividades"},
    "L1DSE110": {"nombre": "Recursos naturales", "nivelacion": "actividades"},
    "O1CO305": {"nombre": "Coaching grupal", "nivelacion": "actividades"},
    "O1IS308": {"nombre": "Gestión de la calidad: testing", "nivelacion": "actividades"},
    "O1PR307": {"nombre": "Transparencia y acceso a la información", "nivelacion": "actividades"},
    "L1PD112": {"nombre": "Organización y gestión de las instituciones educativas", "nivelacion": "actividades"},
    "O1OR307": {"nombre": "Planificación de recursos empresariales", "nivelacion": "actividades"},
    "L1TI202": {"nombre": "Sistemas de información empresarial", "nivelacion": "actividades"},
    "O1AD303": {"nombre": "Sistemas de planificación y organización", "nivelacion": "actividades"},
    "O1CD306": {"nombre": "Comunicación a través de dispositivos móviles e inalámbricos", "nivelacion": "actividades"},
    "L2DE134": {"nombre": "Derecho Financiero", "nivelacion": "actividades"},
    "O1RF301": {"nombre": "Administración de riesgos financieros", "nivelacion": "examen"},
    "L1AD108": {"nombre": "Administración de riesgos", "nivelacion": "examen"},
    "L1AD103": {"nombre": "Administración del capital humano", "nivelacion": "examen"},
    "O1IS307": {"nombre": "Ambientes de desarrollo y frameworks", "nivelacion": "examen"},
    "L1CO113": {"nombre": "Auditoría II", "nivelacion": "examen"},
    "L1DSE101": {"nombre": "Biología general", "nivelacion": "examen"},
    "L1CC118": {"nombre": "Ciencias Forenses", "nivelacion": "examen"},
    "O1CO302": {"nombre": "Competencias del coach", "nivelacion": "examen"},
    "L1C120": {"nombre": "Comportamiento del consumidor", "nivelacion": "examen"},
    "L1OR202": {"nombre": "Comunicación organizacional", "nivelacion": "examen"},
    "L1CO102": {"nombre": "Contabilidad financiera II", "nivelacion": "examen"},
    "L1EM306": {"nombre": "Contratos mercantiles y bancarios", "nivelacion": "examen"},
    "L2DE124": {"nombre": "Contratos mercantiles y bancarios", "nivelacion": "examen"},
    "L1DE109": {"nombre": "Delitos en particular", "nivelacion": "examen"},
    "L2DE109": {"nombre": "Delitos en particular", "nivelacion": "examen"},
    "L1FI204": {"nombre": "Derecho financiero y bursátil", "nivelacion": "examen"},
    "L1DSE114": {"nombre": "Dinámica ambiental", "nivelacion": "examen"},
    "L1IS105": {"nombre": "Electrónica", "nivelacion": "examen"},
    "L1MK105": {"nombre": "Estrategias de precios", "nivelacion": "examen"},
    "O1CO301": {"nombre": "Filosofía del coaching", "nivelacion": "examen"},
    "L1CM104": {"nombre": "Géneros periodísticos", "nivelacion": "examen"},
    "L1TI201": {"nombre": "Introducción a las tecnologías de la información", "nivelacion": "examen"},
    "L1CM113": {"nombre": "Legislación de la comunicación", "nivelacion": "examen"},
    "L1MK112": {"nombre": "Mercadotecnia en la Web", "nivelacion": "examen"},
    "O1FI302": {"nombre": "Métodos computacionales para finanzas", "nivelacion": "examen"},
    "L1OR201": {"nombre": "Organización y administración del capital humano", "nivelacion": "examen"},
    "L1CC119": {"nombre": "Penología", "nivelacion": "examen"},
    "O1OR301": {"nombre": "Planeación estratégica de recursos humanos", "nivelacion": "examen"},
    "L1CPA111": {"nombre": "Política comparada", "nivelacion": "examen"},
    "L1AD104": {"nombre": "Relaciones individuales de trabajo y seguridad social", "nivelacion": "examen"},
    "L1II107": {"nombre": "Sistemas de información en la empresa", "nivelacion": "examen"},
    "L1IS107": {"nombre": "Sistemas digitales y periféricos", "nivelacion": "examen"},
    "L1NE105": {"nombre": "Técnicas de negociación internacional", "nivelacion": "examen"},
    "L1TI204": {"nombre": "Tecnologías de información en la estrategia de negocio", "nivelacion": "examen"},
    "L1CM106": {"nombre": "Teorías contemporáneas de la comunicación", "nivelacion": "examen"},
    "M1ED108": {"nombre": "Diseño de Programas de Enseñanza", "nivelacion": "actividades"},
    "M1ED111": {"nombre": "Diseño de Proyectos de Innovación Educativa", "nivelacion": "actividades"},
    "M1ED107": {"nombre": "Evaluación del Aprendizaje", "nivelacion": "actividades"},
    "M1ITA116B": {"nombre": "Proyectos de maestría", "nivelacion": "actividades"},
    "M1AP111B": {"nombre": "Análisis de proyectos Aplicados a la Administración Pública", "nivelacion": "actividades"},
    "M1ITA113B": {"nombre": "Energías alternativas y su impacto ambiental", "nivelacion": "actividades"},
    "M1GDS09B": {"nombre": "Finanzas Aplicadas al Sector Salud", "nivelacion": "actividades"},
    "M1DET113B": {"nombre": "Turismo Alternativo y Desarrollo Sustentable", "nivelacion": "actividades"},
    "M1DIS07B": {"nombre": "Dirección y planeación estratégica", "nivelacion": "actividades"},
    "M1DV110B": {"nombre": "Equipos de Ventas", "nivelacion": "actividades"},
    "M1ATI114B": {"nombre": "Gestión del Cambio e Innovación Tecnológica", "nivelacion": "actividades"},
    "M1DET114B": {"nombre": "Gestión Integral de Destinos Turísticos", "nivelacion": "actividades"},
    "M1NAB111B": {"nombre": "Gestión y calidad", "nivelacion": "actividades"},
    "M1CH09B": {"nombre": "Indicadores de Gestión", "nivelacion": "actividades"},
    "M1DET107B": {"nombre": "Política y Planeación Turística", "nivelacion": "actividades"},
    "M1NAB101B": {"nombre": "Antropología alimentaria", "nivelacion": "actividades"},
    "M1NAB106B": {"nombre": "Compras e insumos de alimentos y bebidas", "nivelacion": "actividades"},
    "M1ITA104B": {"nombre": "Metodología de la ciencia y diseño de la investigación", "nivelacion": "actividades"},
    "M1NAB103B": {"nombre": "Operación de establecimientos de alimentos y bebidas", "nivelacion": "actividades"},
    "M1ITA102B": {"nombre": "Seguridad ambiental", "nivelacion": "actividades"},
    "M1ITA105B": {"nombre": "Tecnología ambiental", "nivelacion": "actividades"},
    "M1ITA106B": {"nombre": "Tratamiento de efluentes líquidos", "nivelacion": "actividades"},
    "M1ITA109B": {"nombre": "Valorización y gestión de residuos sólidos", "nivelacion": "actividades"},
    "M1CDN101B": {"nombre": "Fundamentos de Estadística", "nivelacion": "actividades"},
    "M1COP114S": {"nombre": "Conciencia plena en el trabajo", "nivelacion": "actividades"},
    "M1COP112S": {"nombre": "Conciencia plena en la niñez y adolescencia", "nivelacion": "actividades"},
    "M1AN101": {"nombre": "Desarrollo del Capital Humano", "nivelacion": "actividades"},
    "M1GOP109S": {"nombre": "Gestión del cambio en la organización", "nivelacion": "actividades"},
    "M1DPC108B": {"nombre": "Derecho Constitucional y Sistemas de Control y Defensa Constitucionales", "nivelacion": "actividades"},
    "M1DPC09B": {"nombre": "Principios y derechos humanos en el ámbito constitucional", "nivelacion": "actividades"},
    "M1DJO107B": {"nombre": "Principios y derechos humanos en el ámbito privado", "nivelacion": "actividades"},
    "M1NAB105B": {"nombre": "Legislación y normatividad", "nivelacion": "actividades"},
    "M1CDN102B": {"nombre": "Investigación de Operaciones", "nivelacion": "actividades"},
    "M1CIO103B": {"nombre": "Elementos y Dinámica Organizacional", "nivelacion": "actividades"},
    "M1CCT05B": {"nombre": "Metodología de la investigación", "nivelacion": "actividades"},
    "M1NAB104B": {"nombre": "Metodología de la investigación", "nivelacion": "actividades"},
    "M1CCT11B": {"nombre": "Temas selectos de redes de computadoras y telefonía", "nivelacion": "actividades"},
    "M1CCT04B": {"nombre": "Teoría de la información y códigos", "nivelacion": "actividades"},
    "M1CCT12B": {"nombre": "Tópicos especializados en telecomunicaciones", "nivelacion": "actividades"},
    "M1AN115": {"nombre": "Coaching Ejecutivo", "nivelacion": "actividades"},
    "M1AN104": {"nombre": "Comportamiento y Ética Organizacional", "nivelacion": "actividades"},
    "M1ED104": {"nombre": "Comunicación Educativa", "nivelacion": "actividades"},
    "M1ME104B": {"nombre": "Ética en la Mercadotecnia", "nivelacion": "actividades"},
    "M1DJO106B": {"nombre": "Ética Profesional", "nivelacion": "actividades"},
    "M1ED105": {"nombre": "Metodologías para la Enseñanza", "nivelacion": "actividades"},
    "M1CH104B": {"nombre": "Modelos y Estrategias para el Desarrollo de Talento", "nivelacion": "actividades"},
    "M1CH102B": {"nombre": "Plataformas tecnológicas", "nivelacion": "actividades"},
    "M1AND107B": {"nombre": "Publicidad en el Deporte ", "nivelacion": "actividades"},
    "M1GDS105": {"nombre": "Estrategias de Mercadotecnia en el Sector Salud A", "nivelacion": "actividades"},
    "M1GDS108B": {"nombre": "Estrategias de Mercadotecnia en el Sector Salud", "nivelacion": "actividades"},
    "M1GDS114B": {"nombre": "Sistemas de Calidad y Seguridad en los Servicios de Salud", "nivelacion": "actividades"},
    "M1ME103B": {"nombre": "Mercadotecnia Estratégica", "nivelacion": "actividades"},
    "M1ITA110B": {"nombre": "Evaluación del riesgo e impacto ambiental", "nivelacion": "actividades"},
    "M1ITA115B": {"nombre": "Gestión ambiental de la empresa", "nivelacion": "actividades"},
    "M1ITA112B": {"nombre": "Tratamiento y recuperación de suelos", "nivelacion": "actividades"},
    "M1AN107": {"nombre": "Contabilidad Administrativa", "nivelacion": "actividades"},
    "M1CIO113B": {"nombre": "Coaching Sistémico y Gestalt", "nivelacion": "actividades"},
    "M1COP113S": {"nombre": "Conciencia plena en la adultez y vejez", "nivelacion": "actividades"},
    "M1GOP107S": {"nombre": "Inteligencia interpersonal", "nivelacion": "actividades"},
    "M1GOP115S": {"nombre": "Introducción a la práctica positiva", "nivelacion": "actividades"},
    "M1COP111S": {"nombre": "Métodos de conciencia plena", "nivelacion": "actividades"},
    "M1GOP108S": {"nombre": "Perseverancia y esfuerzo", "nivelacion": "actividades"},
    "M1COP110S": {"nombre": "Bienestar pleno", "nivelacion": "actividades"},
    "M1COP109S": {"nombre": "Mindfulness (conciencia plena)", "nivelacion": "actividades"},
    "M1DPI104B": {"nombre": "Diseño y desarrollo de productos", "nivelacion": "actividades"},
    "M1DIS01B": {"nombre": "Ingeniería de requisitos, análisis y diseño de software", "nivelacion": "actividades"},
    "M1DIS02B": {"nombre": "Metodología de la investigación", "nivelacion": "actividades"},
    "M1GDS111B": {"nombre": "Sistemas de Información en el sector salud", "nivelacion": "actividades"},
    "M1DIS08B": {"nombre": "Sociedad del conocimiento y cambio de paradigmas", "nivelacion": "actividades"},
    "M1CDN114B": {"nombre": "Toma de Decisiones Basada en Datos", "nivelacion": "actividades"},
    "M1CDN110B": {"nombre": "Visualización de Datos", "nivelacion": "actividades"},
    "M1CDN107B": {"nombre": "Desarrollo de Competencias Analíticas en la Empresa", "nivelacion": "actividades"},
    "M1GDS113B": {"nombre": "Decisiones Estratégicas en el Sector Salud", "nivelacion": "actividades"},
    "M2AN107": {"nombre": "Derecho Corporativo", "nivelacion": "actividades"},
    "M1GDS105B": {"nombre": "Derecho Corporativo", "nivelacion": "actividades"},
    "M1DPC110B": {"nombre": "Derecho Procesal Laboral", "nivelacion": "actividades"},
    "M1AP113B": {"nombre": "Implementación y Análisis de Políticas Públicas", "nivelacion": "actividades"},
    "M1AP108B": {"nombre": "Marco Jurídico de la Administración Pública", "nivelacion": "actividades"},
    "M1DPP107B": {"nombre": "Principios y Derechos Humanos en el Ámbito Penal", "nivelacion": "actividades"},
    "M1DPC107B": {"nombre": "Procesal Constitucional", "nivelacion": "actividades"},
    "M1AP116B": {"nombre": "Seminario Aplicado a la Administración Pública II", "nivelacion": "actividades"},
    "M1DPI107B": {"nombre": "Liderazgo y toma de decisiones", "nivelacion": "actividades"},
    "M1ED103": {"nombre": "Estrategias de Aprendizaje", "nivelacion": "actividades"},
    "M1COP108S": {"nombre": "Pensamiento positivo y conciencia plena", "nivelacion": "actividades"},
    "M1DIS11B": {"nombre": "Cómputo ubicuo", "nivelacion": "actividades"},
    "M1DIS14B": {"nombre": "Formulación y evaluación de proyectos tecnológicos", "nivelacion": "actividades"},
    "M1CCT14B": {"nombre": "Medios tecnológicos innovadores en entornos virtuales", "nivelacion": "actividades"},
    "M1CCT10B": {"nombre": "Sistemas de información geográfica", "nivelacion": "actividades"},
    "M1CCT08B": {"nombre": "Tópicos avanzados de seguridad de la información en medios digitales", "nivelacion": "actividades"},
    "M1NAB107B": {"nombre": "Cadena de producción", "nivelacion": "actividades"},
    "M1CN114B": {"nombre": "Arbitraje Comercial", "nivelacion": "actividades"},
    "M1CN113B": {"nombre": "Compra-Venta Internacional de Mercaderías", "nivelacion": "actividades"},
    "M1DV104B": {"nombre": "Proceso de Ventas", "nivelacion": "actividades"},
    "M1CN103B": {"nombre": "Teoría General del Acto de Comercio", "nivelacion": "actividades"},
    "M1CN111B": {"nombre": "Tratados comerciales internacionales", "nivelacion": "actividades"},
    "M1NAB112B": {"nombre": "Seminario de integración I", "nivelacion": "actividades"},
    "M1ED115": {"nombre": "Educación a Distancia", "nivelacion": "actividades"},
    "M1ITA108B": {"nombre": "Economía de proyectos ambientales", "nivelacion": "actividades"},
    "M1DET112B": {"nombre": "Manejo de riesgos y Contingencias en la Hospitalidad", "nivelacion": "actividades"},
    "M1ITA111B": {"nombre": "Tratamiento de efluentes gaseosos", "nivelacion": "actividades"},
    "M1NAB109B": {"nombre": "Recursos humanos", "nivelacion": "actividades"},
    "M1DJO115B": {"nombre": "Seminario Práctico de Oralidad", "nivelacion": "actividades"},
    "M1CDN115B": {"nombre": "Productos de Datos", "nivelacion": "actividades"},
    "M1DV112B": {"nombre": "Pronóstico de Negocios", "nivelacion": "actividades"},
    "M1CCT06B": {"nombre": "Complejidad computacional", "nivelacion": "actividades"},
    "M1ED114": {"nombre": "Educación de Adultos", "nivelacion": "actividades"},
    "M1AP112B": {"nombre": "Enfoques Metodológicos y Nuevas Tecnologías", "nivelacion": "actividades"},
    "M1ED102": {"nombre": "Filosofía de la Educación", "nivelacion": "actividades"},
    "M1DV103B": {"nombre": "Liderazgo Organizacional", "nivelacion": "actividades"},
    "M1CDN106B": {"nombre": "Liderazgo Tecnológico", "nivelacion": "actividades"},
    "M1CDN108B": {"nombre": "Programación y Algoritmos", "nivelacion": "actividades"},
    "M1AN112": {"nombre": "Tecnología de Información para la Toma de Decisiones", "nivelacion": "actividades"},
    "M1CH107B": {"nombre": "Tecnologías para la Gestión del Conocimiento", "nivelacion": "actividades"},
    "M1CN107B": {"nombre": "Contratación Internacional", "nivelacion": "actividades"},
    "M1DPI101B": {"nombre": "Análisis de tendencias de innovación", "nivelacion": "actividades"},
    "M1DET109B": {"nombre": "Arquitectura tecnológica empresarial", "nivelacion": "actividades"},
    "M1CDN111B": {"nombre": "Big Data Empresarial", "nivelacion": "actividades"},
    "M1DIS13B": {"nombre": "Diseño y explotación de Datawarehouse para Business Intelligence", "nivelacion": "actividades"},
    "M1CDN103B": {"nombre": "Ética y Gestión de la Información", "nivelacion": "actividades"},
    "M1AP105B": {"nombre": "Ética y Trasparencia Pública", "nivelacion": "actividades"},
    "M1ATI107B": {"nombre": "Gestión de Inversiones en Tecnologías de Información", "nivelacion": "actividades"},
    "M1DET110B": {"nombre": "Inteligencia de Negocios", "nivelacion": "actividades"},
    "M1CDN112B": {"nombre": "Introducción a bases de datos", "nivelacion": "actividades"},
    "M1CDN09B": {"nombre": "Métodos predictivos", "nivelacion": "actividades"},
    "M1CCT02B": {"nombre": "Tópicos avanzados de arquitectura de computadoras", "nivelacion": "actividades"},
    "M1AN103": {"nombre": "Administración de la Cadena de Valor", "nivelacion": "actividades"},
    "M1AN106": {"nombre": "Administración estratégica", "nivelacion": "actividades"},
    "M1ME110B": {"nombre": "Estadística para los Negocios en Mercadotecnia", "nivelacion": "actividades"},
    "M1DV117B": {"nombre": "Estrategia y Organización Comercial", "nivelacion": "actividades"},
    "M1AP110B": {"nombre": "Finanzas públicas", "nivelacion": "actividades"},
    "M1COP107S": {"nombre": "Origenes del Mindfulness (atención plena)", "nivelacion": "actividades"},
    "M1AND111B": {"nombre": "Motivación en el deporte", "nivelacion": "actividades"},
    "M1ED109": {"nombre": "Elaboración de Instrumentos de Evaluación", "nivelacion": "actividades"},
    "M1ED101": {"nombre": "Teorías del aprendizaje", "nivelacion": "actividades"},
    "M1AN109": {"nombre": "Estrategias de Mercadotecnia", "nivelacion": "actividades"},
    "M1CIO105B": {"nombre": "Estructura de la Mente", "nivelacion": "actividades"},
    "M1ME106B": {"nombre": "Investigación de Mercados", "nivelacion": "actividades"},
    "M1DV114B": {"nombre": "Marketing y Ventas Digitales", "nivelacion": "actividades"},
    "M1ME113B": {"nombre": "Mercadotecnia Móvil y Redes Sociales", "nivelacion": "actividades"},
    "M1MDE106B": {"nombre": "Mercadotecnia y ventas digitales", "nivelacion": "actividades"},
    "M1DV101B": {"nombre": "Modelo Decisional del Cliente", "nivelacion": "actividades"},
    "M1MDE105B": {"nombre": "Tendencias Globales del Marketing Digital", "nivelacion": "actividades"},
    "M1CCT15B": {"nombre": "Bases de datos, big data y cloud computing (cómputo de nube)", "nivelacion": "actividades"},
    "M1CCT07B": {"nombre": "Cómputo evolutivo", "nivelacion": "actividades"},
    "M1CCT16B": {"nombre": "Sistemas de cómputo concurrentes, paralelos y distribuidos", "nivelacion": "actividades"},
    "M1GOP113S": {"nombre": "Organizaciones positivas", "nivelacion": "actividades"},
    "M1COP101S": {"nombre": "Bases de la positividad", "nivelacion": "actividades"},
    "M1COP105S": {"nombre": "Estado óptimo de la vida", "nivelacion": "actividades"},
    "M1CCT01B": {"nombre": "Matemáticas discretas", "nivelacion": "actividades"},
    "M1CN110B": {"nombre": "Derecho Aduanero e Incoterms", "nivelacion": "actividades"},
    "M1CN09B": {"nombre": "Derecho Fiscal Internacional", "nivelacion": "actividades"},
    "M1DPC111B": {"nombre": "Derecho Procesal Administrativo y Fiscal", "nivelacion": "actividades"},
    "M1DPC113B": {"nombre": "Juicio de Amparo en Materia Fiscal-Administrativa", "nivelacion": "actividades"},
    "M1DPC114B": {"nombre": "Juicio de Amparo en Materia Laboral", "nivelacion": "actividades"},
    "M1DJO110B": {"nombre": "Juicios Especiales en Materia Mercantil", "nivelacion": "actividades"},
    "M1CN104B": {"nombre": "Marco Jurídico del Comercio Exterior e Inversión Extranjera", "nivelacion": "actividades"},
    "M1DPC112B": {"nombre": "Medios de Impugnación y Ejecución de sentencias en la materia Administrativa y Fiscal", "nivelacion": "actividades"},
    "M1DJO108B": {"nombre": "Procesal Civil Conceptos y Características", "nivelacion": "actividades"},
    "M1DPC115B": {"nombre": "Seminario Procesal Administrativo-Fiscal", "nivelacion": "actividades"},
    "M1CIO101B": {"nombre": "Fundamentos del Comportamiento Humano 1", "nivelacion": "actividades"},
    "M1ED106": {"nombre": "Teoría y Desarrollo Curricular", "nivelacion": "actividades"},
    "M1ATI110B": {"nombre": "Administración de proyectos", "nivelacion": "actividades"},
    "M1CIO108B": {"nombre": "Coaching Ejecutivo 1", "nivelacion": "actividades"},
    "M1CIO112B": {"nombre": "Coaching Ejecutivo 2", "nivelacion": "actividades"},
    "M1CIO114B": {"nombre": "Coaching Ejecutivo 3", "nivelacion": "actividades"},
    "M1CIO107B": {"nombre": "Competencias de Coaching", "nivelacion": "actividades"},
    "M1CH112B": {"nombre": "Cultura y Relaciones Laborales", "nivelacion": "actividades"},
    "M1DV107B": {"nombre": "Ejecución Estratégica", "nivelacion": "actividades"},
    "M1ED112": {"nombre": "Elaboración de Programas por Competencias", "nivelacion": "actividades"},
    "M1ARH106B": {"nombre": "Formación y Desarrollo de Recursos Humanos", "nivelacion": "actividades"},
    "M1CH103B": {"nombre": "Fundamentos del Comportamiento Humano", "nivelacion": "actividades"},
    "M1CIO09B": {"nombre": "Gestión del Cambio", "nivelacion": "actividades"},
    "M1CH111B": {"nombre": "Modelos de Aprendizaje Organizacional", "nivelacion": "actividades"},
    "M1DIS04B": {"nombre": "Principios de administración general", "nivelacion": "actividades"},
    "M1DIS06B": {"nombre": "Psicología del trabajo y gestión de recursos humanos", "nivelacion": "actividades"},
    "M1AP101B": {"nombre": "Administración Pública en México", "nivelacion": "actividades"},
    "M1AN110": {"nombre": "Fundamentos y Procesos del Coaching", "nivelacion": "actividades"},
    "M1DPI106B": {"nombre": "Dirección estratégica", "nivelacion": "actividades"},
    "M1AND105B": {"nombre": "Diseño y Estructura Organizacional de Entidades Deportivas", "nivelacion": "actividades"},
    "M1AND113B": {"nombre": "Gestión Deportiva", "nivelacion": "actividades"},
    "M1CH113B": {"nombre": "Gestión Estratégica de la Capacitación", "nivelacion": "actividades"},
    "M1AND116B": {"nombre": "Industria Deportiva", "nivelacion": "actividades"},
    "M1COP116S": {"nombre": "Práctica positiva", "nivelacion": "actividades"},
    "M1DJO113B": {"nombre": "Ejecución de Sentencias y Medios de Impugnación", "nivelacion": "actividades"},
    "M1AP102B": {"nombre": "Gobierno y Sociedad Civil", "nivelacion": "actividades"},
    "M1DJO112B": {"nombre": "Juicio Oral y Procedimientos en Materia de Familia", "nivelacion": "actividades"},
    "M1DJO111B": {"nombre": "Juicios Especiales en Materia Civil", "nivelacion": "actividades"},
    "M1DJO105B": {"nombre": "Medios Alternos de Solución de Controversias", "nivelacion": "actividades"},
    "M1DJO109B": {"nombre": "Procesal Mercantil Conceptos y Características", "nivelacion": "actividades"},
    "M1ED110": {"nombre": "Multimedia Educativa", "nivelacion": "actividades"},
    "M1DIS15B": {"nombre": "Técnicas y aplicaciones de Big Data", "nivelacion": "actividades"},
    "M1DIS12B": {"nombre": "Técnicas y herramientas de la mediación científica, tecnológica y económica", "nivelacion": "actividades"},
    "M1CH116B": {"nombre": "Administración de la Compensación", "nivelacion": "actividades"},
    "M1CIO106B": {"nombre": "Coaching Ontológico 1", "nivelacion": "actividades"},
    "M1CIO110B": {"nombre": "Coaching ontológico 2", "nivelacion": "actividades"},
    "M1AND112B": {"nombre": "Estrategias de Mercadotecnia en el Deporte", "nivelacion": "actividades"},
    "M1MDE114B": {"nombre": "Marketing en buscadores, posicionamiento y análisis web", "nivelacion": "actividades"},
    "M1AN105": {"nombre": "Mercadotecnia", "nivelacion": "actividades"},
    "M1CDN104B": {"nombre": "Metodología de la Ciencia de Datos En ciencia de datos para negocios", "nivelacion": "actividades"},
    "M1DV111B": {"nombre": "Negociación", "nivelacion": "actividades"},
    "M1ARH114B": {"nombre": "Planeación Estratégica de Programas de Recursos Humanos", "nivelacion": "actividades"},
    "M1AP114B": {"nombre": "Seminario Aplicado a la Administración Pública I", "nivelacion": "actividades"},
    "M1CIO111B": {"nombre": "Transformación Personal", "nivelacion": "actividades"},
    "M1ITA107B": {"nombre": "Desarrollo sustentable", "nivelacion": "actividades"},
    "M1ITA114B": {"nombre": "Ética ambiental", "nivelacion": "actividades"},
    "M1DIS09B": {"nombre": "Habilidades gerenciales y liderazgo organizacional", "nivelacion": "actividades"},
    "M1COP106S": {"nombre": "Ciencia de la felicidad", "nivelacion": "actividades"},
    "M1GOP110S": {"nombre": "Diagnóstico y Autoconocimiento", "nivelacion": "actividades"},
    "M1ME105B": {"nombre": "E-Commerce y Mercadotecnia en la Web", "nivelacion": "actividades"},
    "M1AIE113B": {"nombre": "Elaboración de Instrumentos de Evaluación para la Gestión Educativa", "nivelacion": "actividades"},
    "M1CH108B": {"nombre": "Estrategia y Gestión del Cambio", "nivelacion": "actividades"},
    "M1DPI103B": {"nombre": "Estrategias empresariales y de innovación", "nivelacion": "actividades"},
    "M1ARH113B": {"nombre": "Gestión del Cambio e Innovación", "nivelacion": "actividades"},
    "M1AN108": {"nombre": "Habilidades Directivas A", "nivelacion": "actividades"},
    "M1AN114": {"nombre": "Inteligencia Emocional A", "nivelacion": "actividades"},
    "M1NAB108B": {"nombre": "Liderazgo y dirección empresarial", "nivelacion": "actividades"},
    "M1ME111B": {"nombre": "Mercadotecnia Digital", "nivelacion": "actividades"},
    "M1COP104S": {"nombre": "Metas para la vida", "nivelacion": "actividades"},
    "M1DV102B": {"nombre": "Psicología del consumidor", "nivelacion": "actividades"},
    "M1ITA101B": {"nombre": "Fundamentos de la ingeniería ambiental", "nivelacion": "actividades"},
    "M1DIS03B": {"nombre": "Metodologías de desarrollo de software", "nivelacion": "actividades"},
    "M1CDN113B": {"nombre": "Métodos de Detección de Patrones", "nivelacion": "actividades"},
    "M1CIO102B": {"nombre": "Autoconocimiento", "nivelacion": "actividades"},
    "M1DV113B": {"nombre": "Compras", "nivelacion": "actividades"},
    "M1DV115B": {"nombre": "Comunicación Comercial", "nivelacion": "actividades"},
    "M1COP103S": {"nombre": "Fortalezas del carácter", "nivelacion": "actividades"},
    "M1CH114B": {"nombre": "Gestión del Desempeño", "nivelacion": "actividades"},
    "M1CH106B": {"nombre": "Herramientas para la Gestión del Talento 1", "nivelacion": "actividades"},
    "M1CH110B": {"nombre": "Herramientas para la Gestión del Talento 2", "nivelacion": "actividades"},
    "M1COP102S": {"nombre": "Perspectivas del bienestar", "nivelacion": "actividades"},
    "M1GDS110B": {"nombre": "Proyección profesional", "nivelacion": "actividades"},
    "M1CH101B": {"nombre": "Rediseño de la Función del Capital Humano", "nivelacion": "actividades"},
    "M1CH105B": {"nombre": "Seguridad Ocupacional", "nivelacion": "actividades"},
    "M1DV105B": {"nombre": "Canales de distribución", "nivelacion": "actividades"},
    "M1DV106B": {"nombre": "Dirección y Gestión de Equipos", "nivelacion": "actividades"},
    "M1ED113": {"nombre": "Evaluación de programas", "nivelacion": "actividades"},
    "M1ITA103B": {"nombre": "Legislación y normatividad ambiental", "nivelacion": "actividades"},
    "M1DJO103B": {"nombre": "Lógica y Argumentación Jurídica", "nivelacion": "actividades"},
    "M1DPP108B": {"nombre": "Nuevo Sistema Penal Mexicano", "nivelacion": "actividades"},
    "M1AN102": {"nombre": "Administración de las Organizaciones", "nivelacion": "actividades"},
    "M1AP107B": {"nombre": "Economía Pública: Macroeconomía y Microeconomía", "nivelacion": "actividades"},
    "M1GDS112": {"nombre": "Economía y salud", "nivelacion": "actividades"},
    "M1GDS116B": {"nombre": "Economía y salud", "nivelacion": "actividades"},
    "M1AP115B": {"nombre": "Estadística Aplicada a las Políticas Públicas", "nivelacion": "actividades"},
    "M1DV109B": {"nombre": "Estrategia de Precios", "nivelacion": "actividades"},
    "M1AN113": {"nombre": "Estrategias Financieras", "nivelacion": "actividades"},
    "M1AN111": {"nombre": "Finanzas Corporativas", "nivelacion": "actividades"},
    "M1FI113": {"nombre": "Finanzas Corporativas", "nivelacion": "actividades"},
    "M1DV108B": {"nombre": "Finanzas en las Ventas", "nivelacion": "actividades"},
    "M1NAB110B": {"nombre": "Finanzas y contabilidad", "nivelacion": "actividades"},
    "M1CIO104B": {"nombre": "Fundamentos del Coaching", "nivelacion": "actividades"},
    "M1ARH110B": {"nombre": "Relaciones Laborales en la Empresa", "nivelacion": "actividades"},
    "M1CN115B": {"nombre": "Seminario de Comercio Internacional", "nivelacion": "actividades"},
    "M1AP109B": {"nombre": "Gestión Pública", "nivelacion": "actividades"},
    "M1GDS112B": {"nombre": "Marco Legal en el Sector Salud", "nivelacion": "actividades"},
    "M1DJO104B": {"nombre": "Principios Generales del Derecho Procesal", "nivelacion": "actividades"},
    "M1DPP112B": {"nombre": "Principios y Generalidades del Sistema Acusatorio Adversarial", "nivelacion": "actividades"},
    "M1DPP106B": {"nombre": "Proceso Penal. Conceptos y Características", "nivelacion": "actividades"},
    "M1DPP110B": {"nombre": "Sujetos del Sistema Penal", "nivelacion": "actividades"},
    "M1DPP111B": {"nombre": "Teoría de los Presupuestos Tipológicos de los Delitos", "nivelacion": "actividades"},
    "M1DIS10B": {"nombre": "Creatividad e innovación tecnológica", "nivelacion": "actividades"},
    "M1DPI102B": {"nombre": "Creatividad e innovación tecnológica", "nivelacion": "actividades"},
    "M1DIS16B": {"nombre": "Desarrollo integral de proyectos tecnológicos", "nivelacion": "actividades"},
    "M1ATI113B": {"nombre": "Estrategias de Negocios Electrónicos", "nivelacion": "actividades"},
    "M1CCT13B": {"nombre": "Ingeniería de software y sistemas operativos", "nivelacion": "actividades"},
    "M1CDN105B": {"nombre": "Introducción a la Modelación y Series de Tiempo", "nivelacion": "actividades"},
    "M1CCT09B": {"nombre": "Lenguajes de programación y compiladores", "nivelacion": "actividades"},
    "M1MDE110B": {"nombre": "Marketing para E-Commerce", "nivelacion": "actividades"},
    "M1DIS05B": {"nombre": "Modelos y estándares de calidad de software", "nivelacion": "actividades"},
    "M1CCT03B": {"nombre": "Tópicos de inteligencia artificial", "nivelacion": "actividades"},
    "M1ME108B": {"nombre": "Contabilidad Administrativa y Finanzas Corporativas", "nivelacion": "actividades"},
    "M1AP106B": {"nombre": "Liderazgo en la Administración Pública", "nivelacion": "actividades"},
    "M1DPI105B": {"nombre": "Seguridad y fiabilidad en el proyecto", "nivelacion": "actividades"},
    "M1NAB115B": {"nombre": "Seminario de integración II", "nivelacion": "actividades"},
    "M1NAB114B": {"nombre": "Emprendimiento empresarial", "nivelacion": "actividades"},
    "M1NAB116B": {"nombre": "Ética empresarial", "nivelacion": "actividades"},
    "M1DJO102B": {"nombre": "Derechos humanos", "nivelacion": "actividades"},
    "M1DPP113B": {"nombre": "Etapas del sistema acusatoria adversarial", "nivelacion": "actividades"},
    "M1DJO114B": {"nombre": "Juicio de Amparo en materia Civil", "nivelacion": "actividades"},
    "M1DPP114B": {"nombre": "Juicio de amparo en materia penal", "nivelacion": "actividades"},
    "M1DPP115B": {"nombre": "Seminario del Sistema Acusatorio Adversarial", "nivelacion": "actividades"},
    "M1DJO101B": {"nombre": "Teoría General del Proceso", "nivelacion": "actividades"}
    # ← Agrega aquí el resto de tus materias
}

# 🔍 Invertimos el diccionario para buscar por nombre normalizado
materias_por_nombre = {
    unidecode(v["nombre"].strip().lower()): {"clave": k, "nivelacion": v["nivelacion"]}
    for k, v in materias.items()
}

@app.route('/', methods=['GET', 'POST'])
def index():
    resultados = []
    mensaje = ""

    # 🧮 Contador de visitas usando SQLite
    try:
        conn = sqlite3.connect("visitas.db")
        cursor = conn.cursor()

        cursor.execute("SELECT contador FROM visitas LIMIT 1")
        row = cursor.fetchone()

        if row:
            contador = row[0] + 1
            cursor.execute("UPDATE visitas SET contador = ?", (contador,))
        else:
            contador = 1
            cursor.execute("INSERT INTO visitas (contador) VALUES (?)", (contador,))

        conn.commit()
        conn.close()

    except Exception as e:
        print("Error en contador de visitas:", e)
        contador = "?"

    if request.method == 'POST':
        texto = request.form['materias']
        lineas = texto.strip().split('\n')

        for entrada in lineas:
            entrada_normalizada = unidecode(entrada.strip().lower())
            if not entrada_normalizada:
                continue

            encontrado = False
            for clave, datos in materias.items():
                nombre_normalizado = unidecode(datos['nombre'].lower())
                if nombre_normalizado == entrada_normalizada:
                    resultados.append({
                        'nombre': datos['nombre'],
                        'clave': clave,
                        'nivelacion': datos['nivelacion']
                    })
                    encontrado = True
                    break

            if not encontrado:
                resultados.append({
                    'nombre': entrada.strip().title(),
                    'clave': '',
                    'nivelacion': ''
                })

        if not resultados:
            mensaje = "No se ingresaron materias válidas."

    return render_template('index.html', resultados=resultados, mensaje=mensaje, contador=contador)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=3000)
